_container_id := ""

_default:
  @just --list

stop:
  sudo docker compose stop

start:
  sudo docker compose up -d

start_fg:
  sudo docker compose up

exec *ARGS:
  sudo docker exec -it {{_container_id}} {{ARGS}}

sh:
  @just exec sh

console *ARGS:
  @just exec /var/www/wallabag/bin/console --env=prod {{ARGS}}

migrate:
  @just console doctrine:migrations:migrate

dbshell:
  PGPASSWORD=<password> psql -U wallabag -h 127.0.0.1

redis:
  redis-cli -p 6380

logs:
  @just exec tail -f /var/www/wallabag/var/logs/prod.log
