version: '3.1'

services:
    wallabag:
        image: wallabag/wallabag
        restart: always
        environment:
            # For more config, refer: https://hub.docker.com/r/wallabag/wallabag/
            SYMFONY__ENV__SECRET: ${SECRET:?error}
            SYMFONY__ENV__DATABASE_DRIVER: ${DB_DRIVER:-pdo_pgsql}
            SYMFONY__ENV__DATABASE_HOST: ${DB_HOST:-host.docker.internal}
            SYMFONY__ENV__DATABASE_PORT: ${DB_PORT:-5432}
            SYMFONY__ENV__DATABASE_NAME: ${DB_NAME:-wallabag}
            SYMFONY__ENV__DATABASE_USER: ${DB_USER:-wallabag}
            SYMFONY__ENV__DATABASE_PASSWORD: ${DB_PASSWORD:?error}
            SYMFONY__ENV__DATABASE_CHARSET: utf8
            # SYMFONY__ENV__LOCALE: en
            # SYMFONY__ENV__MAILER_HOST: 127.0.0.1
            # SYMFONY__ENV__MAILER_USER: ~
            # SYMFONY__ENV__MAILER_PASSWORD: ~
            # SYMFONY__ENV__FROM_EMAIL: wallabag@example.com
            # SYMFONY__ENV__TWOFACTOR_AUTH: true
            # SYMFONY__ENV__TWOFACTOR_SENDER: no-reply@wallabag.org
            SYMFONY__ENV__FOSUSER_REGISTRATION: false
            # SYMFONY__ENV__FOSUSER_CONFIRMATION: true
            SYMFONY__ENV__DOMAIN_NAME: ${DOMAIN_NAME:?error}
            # SYMFONY__ENV__REDIS_SCHEME: tcp  # tcp, unix, or http
            SYMFONY__ENV__REDIS_HOST: ${REDIS_HOST:-host.docker.internal}
            SYMFONY__ENV__REDIS_PORT: ${REDIS_PORT:-6379}
            # SYMFONY__ENV__REDIS_PATH: ~  # (defaults to "~", path of the unix socket file)
            # SYMFONY__ENV__REDIS_PASSWORD: ~
            # SYMFONY__ENV__SENTRY_DSN: ~
            # POPULATE_DATABASE: true
            SYMFONY__ENV__SERVER_NAME: ${SERVER_NAME}
        ports:
            - ${SERVICE_PORT:?error}:80
        volumes:
            - /opt/wallabag/images:/var/www/wallabag/web/assets/images
        extra_hosts:
            - "host.docker.internal:host-gateway"

