_container_id := ""

_default:
    @just --list

stop:
    sudo docker compose stop

start:
    sudo docker compose up -d
    sudo docker ps | rg wallabag

start_fg:
    sudo docker compose up

exec *ARGS:
    sudo docker exec -it {{ _container_id }} {{ ARGS }}

sh:
    @just exec sh

console *ARGS:
    @just exec /var/www/wallabag/bin/console --env=prod {{ ARGS }}

migrate:
    @just console doctrine:migrations:migrate

logs:
    @just exec tail -f /var/www/wallabag/var/logs/prod.log
